version: 2.1 # Use 2.1 to enable using orbs and other features.

orbs: 
  browser-tools: circleci/browser-tools@1.2.4
jobs:
  build:
    docker:
      - image: cimg/ruby:2.7.5-browsers
        environment:
          - BUNDLER_VERSION: 2.2.26
          - RAILS_ENV: test
          - PGHOST: 127.0.0.1
      - image: circleci/postgres:13.4
        environment:
          - POSTGRES_USER: macro_store
          - POSTGRES_PASSWORD: "true"
          - POSTGRES_DB: macro_store_test # macro_storeのテスト環境を参照
    working_directory: ~/macro_store

    steps:
      - checkout # ~/macro_storeディレクトリ内にgithubのコードをプルダウンする
      - browser-tools/install-browser-tools
      - run:
          command: |
            google-chrome --version
            chromedriver --version
      - run:
          name: "Update of node.js and npm"
          command: |
            curl -sSL "https://nodejs.org/dist/v14.17.0/node-v14.17.0-linux-x64.tar.xz" | sudo tar --strip-components=2 -xJ -C /usr/local/bin/ node-v14.17.0-linux-x64/bin/node
            curl https://www.npmjs.com/install.sh | sudo bash
      - restore_cache: # 以下がキャッシュされていれば使用する
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }}
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: install dependencies
          command: |
            gem install bundler -v 2.2.26
            bundle install --jobs=4 --retry=3 --path vendor/bundle
            yarn add node-sass
            yarn install --frozen-lockfile --cache-folder ~/.cache/yarn
      - save_cache: #ファイルをキャッシュする
          paths:
            - ./vendor/bundle #キャッシュするファイルの指定
          key: v1-dependencies-{{ checksum "Gemfile.lock" }} #キャッシュの名前
      - save_cache:
          paths:
            - ~/.cache/yarn
          key: yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Database setup
          command: |
            bundle exec rails db:create
            bundle exec rails db:schema:load
            bundle exec rails db:seed
      - run:
          name: Rubocop
          command: bundle exec rubocop
      - run:
          name: rails-best-practice
          command: bundle exec rails_best_practices
      - run:
          name: lint
          command: yarn run lint
      - run:
          name: rspec
          command: COVERALLS_REPO_TOKEN=$COVERALLS_REPO_TOKEN bundle exec rspec
